instagram/urls.py
from django.contrib import admin
from django.conf.urls import include,url

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'', include('postings.urls')),
    #url(r'accounts/profile/', include('django_registration.backends.one_step.urls')),
]

postings/urls.py
from django.contrib.auth.decorators import login_required

from postings.models import Post
from . import views
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'postings'

urlpatterns = [
    path(r'',views.PostFeedView.as_view(),name='feed'),
    path(r'posts/new/',views.CreatePostView.as_view(),name='create_post'),
    path(r'posts/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
    path(r'profile/<str:username>/',views.UserDetailView.as_view(),name='user_detail'),
    path(r'login/',auth_views.LoginView.as_view(), name='login'),
    path(r'logout/',views.LogoutView.as_view(),name='logout'),
    path(r'signup/',views.SignupView.as_view(),name='signup'),
    path(r'me/profile/',views.UpdateProfileView.as_view(),name='update'),
]

postings/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('Profile', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    photo = CloudinaryField('photos')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

def __str__(self):
        """Return title and username"""
        return "{} by @{}".format(self.title, self.profile.user)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    picture = CloudinaryField('pictures')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.user.username==None:
            return "ERROR-USER USERNAME IS NULL"
        return self.user.username

postings/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Post

class SignupForm(forms.Form):

    # Por default los valores son requeridos
    username = forms.CharField(
        min_length=5,
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Username','class': 'form-control'})
    )
    password = forms.CharField(
        min_length=8,
        max_length=70,
        widget=forms.PasswordInput(attrs={'placeholder': 'Password','class': 'form-control'})
    )
    password_confirmation = forms.CharField(
        min_length=8,
        max_length=70,
        widget=forms.PasswordInput(attrs={'placeholder': 'Password Confirmation','class': 'form-control'})
    )
    first_name = forms.CharField(
        min_length=2,
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'First name','class': 'form-control'})
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Last name','class': 'form-control'})
    )
    email = forms.CharField(
        min_length=7,
        max_length=70,
        widget=forms.EmailInput(attrs={'placeholder': 'Email','class': 'form-control'})
    )

    def clean_username(self):
        """Username must be unique"""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')
        return data

    def save(self):
        """Create user and profile"""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()
class PostForm(forms.ModelForm):
	"""Post model form"""

	class Meta:
		"""Form settings."""
		model = Post
		fields = ('profile', 'title', 'photo')

postings/views.py
from django.contrib.auth import logout
from django.contrib.auth import views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.urls import reverse, reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, FormView, UpdateView, ListView, DetailView, CreateView
from django.contrib.auth.models import User
from .forms import SignupForm,PostForm
from .models import Post,Profile
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


# Create your views here.

class SignupView(FormView):
    """Signup View."""
    template_name = 'registration/register.html'
    form_class = SignupForm
    success_url = reverse_lazy('postings:login')

    def form_valid(self, form):
        """If the form is valid save the user"""
        form.save()
        return super().form_valid(form)


class LoginView(views.LoginView):
    """Login view"""
    template_name = 'registration/login.html'
    redirect_authenticated_user = True

class LogoutView(LoginRequiredMixin, views.LogoutView):
    """Logout View."""

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update a user's profile view"""
    template_name = 'registration/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']
    # Return success url
    def get_object(self):
        """Return user's profile"""
        return self.request.user.profile
    def get_success_url(self):
        """Return to user's profile."""
        username = self.object.user.username
        return reverse('postings:user_detail', kwargs={'username_slug': username})


class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view."""
    template_name = 'registration/update.html'
    slug_field = 'username'
    slug_url_kwarg = 'username_slug'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context"""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['postings'] = Post.objects.filter(user=user).order_by('-created')
        return context

class CreatePostView(LoginRequiredMixin, CreateView):
    
    """Create New Post View"""
    template_name = 'postings/new_post.html'
    form_class = PostForm
    success_url = reverse_lazy('postings:feed')
    context_object_name = 'form'

    def get_context_data(self, **kwargs):
        """Add User and profile to context."""
        context = super().get_context_data(**kwargs)
        context['profile'] = self.request.user.profile
        return context


class PostFeedView(LoginRequiredMixin, ListView):
    """Return all published posts."""
    template_name = 'postings/all_posts.html'
    model = Post
    ordering = ('-created',)
    paginate_by = 4
    context_object_name = 'posts'


class PostDetailView(LoginRequiredMixin, DetailView):
    """Detail view posts"""
    template_name = 'postings/post_details.html'
    slug_field = 'id'
    slug_url_kwarg = 'post_id'
    queryset = Post.objects.all()
    context_object_name = 'post'

postings/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	{% block head_content %}
	{% endblock head_content %}
	{%load bootstrap4%}

	{% load static %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

</head>
<body>

    {% include "navbar.html" %}
	<span class="container"></span>
    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

	<!--JS libraries-->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

postings/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'postings:feed' %}">
            <img src="{% static 'icons/instagram.png' %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="#">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35"
                                class="d-inline-block align-top rounded-circle"/>
                        {% else %}
                            <img src="{% static 'icons/default-profile.png' %}" height="35"
                                class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'postings:create_post' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'postings:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

postings/templates/postings/all_posts.html
{% extends "base.html" %}

{% block head_content %}
    <title>instagram</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row">

            {% for post in posts %}
                {% include 'postings/design.html' %}
            {% endfor %}
        </div>
    </div>
    {% include 'setup.html' %}
{% endblock %}

postings/templates/postings/design.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1">
        <a href="#">
            <img 
                class="mr-3 rounded-circle"
                height="35" 
                src="{{ post.profile.picture.url }}"
                alt="{{ post.user.get_full_name }}"
            />
        </a>
        <div class="media-body">
            <p style="margin-top: 5px;">{{ post.user.get_full_name }}</p>
        </div>
    </div>

    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">

    <p class="mt-1 ml-2">
        <a href="" style="color: #000; font-size: 20px;">
            <i class="far fa-heart"></i>
        </a> 30 likes
    </p>
    <p class="ml-2 mt-0 mb-2">
        <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
    </p>
</div>

postings/templates/postings/new_post.html
{% extends "base.html" %}

{% block head_content %}
<title>Create new post</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Post a new photo!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="user" value="{{ request.user.pk}}" />
                    <input type="hidden" name="profile" value="{{ request.user.profile.pk }}" />

                    {# Website field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label>Choose your photo:</label>
                        <input
                            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                            type="file"
                            name="photo"
                            placeholder="photo"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

postings/templates/postings/post_details.html
{% extends "base.html" %}

{% block head_content %}
<title>{{ post.title }}</title>
{% endblock %}

{% block container %}

<div class="container">
    <div class="row">
        {% include 'postings/design.html' %}
    </div>
</div>

{% endblock %}

postings/templates/setup.html
<nav class=mt-5>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

templates/data/all_posts.html
{% extends "base.html" %}

{% block head_content %}
    <title>instagram</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row">

            {% for post in posts %}
                {% include 'data/design.html' %}
            {% endfor %}
        </div>
    </div>
    {% include 'setup.html' %}
{% endblock %}

templates/data/design.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <a href="{% url "users:detail" post.profile.user.username %}" style='color: inherit;text-decoration: inherit;'>
        <div class="media pt-3 pl-3 pb-1">
                <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
                <div class="media-body">
                    <p style="margin-top: 5px;">{{ post.profile.user.get_full_name  }}</p>
                </div>
        </div>
    </a>
    <a href="{% url "posts:detail" post.id %}">
        <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">
    </a>
    <p class="mt-1 ml-2" >
        <a href="" style="color: #000; font-size: 20px;">
            <i class="far fa-heart"></i>
        </a> 30 likes
    </p>
    <p class="ml-2 mt-0 mb-2">
        <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
    </p>
</div>

templates/data/post_details.html
{% extends "base.html" %}

{% block head_content %}
<title>{{ post.title }}</title>
{% endblock %}

{% block container %}

<div class="container">
    <div class="row">
        {% include 'data/design.html' %}
    </div>
</div>

{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>Login</title>
{% endblock head_content %}

{% block container %}
	{% if form.errors %}
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
			<p>Your username and password didn't match. Please try again.</p>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    			<span aria-hidden="true">&times;</span>
  			</button>
		</div>
	{% endif %}
	{% if message %}
		<div class="alert alert-info alert-dismissible fade show" role="alert">
			{{message}}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    			<span aria-hidden="true">&times;</span>
  			</button>
		</div>
	{% endif %}
	<form method="POST" action="{% url 'users:login' %}">
		{% csrf_token %}
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Username" name="username">
		</div>
		<div class="form-group">
			<input type="password" class="form-control" placeholder="Password" name="password">
		</div>

		<button type="submit" class="btn btn-outline-info btn-block mt-5"><i class="lead">Sign in!</i></button>	
	</form>
	<div class="mx-auto mt-1" style="width: 300px;">
		<p>Not registered? <a href="{% url "users:signup" %}">Create an account</a></p>
	</div>
{% endblock container %}

templates/users/register.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>Signup</title>
{% endblock head_content %}
{% block container %}
	{% if form.errors %}
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
			{{form.errors}}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    			<span aria-hidden="true">&times;</span>
  			</button>
		</div>
	{% endif %}
	{% if message %}
		<div class="alert alert-info alert-dismissible fade show" role="alert">
			{{message}}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    			<span aria-hidden="true">&times;</span>
  			</button>
		</div>
	{% endif %}
	<form method="POST" action="{% url 'users:signup' %}">
		{% csrf_token %}
		{% for input in form %}
			<div class="form-group">
				{{input}}
			</div>
            <div class="invalid-feedback">
                {% for error in input.errors %}{{ error }}{% endfor %}
            </div>
		{% endfor %}

		<button type="submit" class="btn btn-outline-success btn-block mt-5"><i class="lead">Register!</i></button>	
	</form>
		<div class="mx-auto mt-1" style="width: 300px;">
		<p>Already registered? <a href="{% url "users:login" %}">Sign In</a></p>
	</div>
{% endblock container %}

templates/users/update.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ user.username }} - instagram </title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if user.profile.picture %}
                        <img src="{{ user.profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture" ></p>
                    </div>
                </div>
                {% for error in form.picture.errors %}
                	<div class="alert alert-danger"><b>Picture:</b> {{error}}</div>
                {% endfor %}

                <hr><br>

                <div class="form-group">
                    <label>Website</label>
                    <input
                        class="form-control 
                        {% if form.website.errors %}
                        	is-invalid
                        {% endif %}"
                        type="text"
                        name="website"
                        placeholder="Website"
                        value="{% if form.errors %}{{form.website.value}}{% else %}{{ user.profile.website }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                    	{% for error in form.website.errors %}
                    		{{error}}
                    	{% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                    <textarea
                    	class="form-control 
                        {% if form.biography.errors %}
                        	is-invalid
                        {% endif %}" 
                    	name="biography">{% if form.errors %}{{form.biography.value}}{% else %}{{user.profile.biography }}{% endif %}</textarea>
                	<div class="invalid-feedback">{% for error in form.biography.errors %}{{error}}{% endfor %}</div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control 
                        {% if form.phone_number.errors %}
                        	is-invalid
                        {% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{% if form.errors %}{{form.phone_number.value}}{% else %}{{ user.profile.phone_number }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                    	{% for error in form.phone_number.errors %}
                    		{{error}}
                    	{% endfor %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}